### ISSUE TITLE
Game Engine Roadmap

### ISSUE THREAD

**Issue by rglezg** [rglezg/pokeemerald#2]
This issue is to keep track of all planned / implemented improvements to game mechanics.

Features included in the DizzyEggg Battle Engine are listed [here](https://www.pokecommunity.com/showthread.php?t=417820). However, many of them will be overridden by my own implementations. The Mega Evolution system will **not** be used.

### Pokémon

- [ ] Add all evolutions/pre-evolutions of the original 386 pokémon

- [ ] Balance pokémon stats

- [ ] Change all lvl based and trading based evolutions to be friendship based

- [ ] Add modern evolution machanics

- [ ] Implement "evolution moves"

- [ ] Improve the friendship system

- [ ] Change the types of some mons and moves

### Battle

- [ ] Set all battles to double

- [ ] Disable "Switch" option in battle

- [ ] Improve the EVs gaining system

- [ ] Disable badge boots

- [ ] Dinammically generate pokémon levels

- [ ] Improve white out money calculation

- [ ] Restore all PPs at battle end

### Overworld

- [ ] Implement a day and night system (Visual effect and changes in the wild pokémon areas)

- [ ] Solve the HM slaves problem

- [ ] Allow running indoors

- [ ] Reduce de Pkmn Center nurse dialog

### UI

- [ ] Add nature affected stat coluring

- [ ] Show EVs in stat page

### Game Progression

- [ ] Change starters

- [ ] Allow catching mons before getting the Pokédex

- [ ] Set HMs as rewards for completing the Dex

- [ ] Set obedience limit for all mons
